### ISSUE TITLE
Processes not always killed on exit

### ISSUE THREAD

**Issue by jamescasbon** [nickstenning/honcho#1]
Ocassionally, I am left with all the child processes still running when honcho exits.

Can you be a bit more careful to term the processes?

**Comment by Suor** [comment]
Still an issue for me. Here is how I reproduce it.

1. Run `honcho run celery -A stargeo worker -l info`.
2. Kill process with smallest pid.
3. All the other subprocesses still run.

If instead I use something like:
```bash
source /path/to/virtualenv/bin/activate

export DEBUG=True
export DATABASE_URL="postgres://postgres@localhost/db_name"
export SECRET_KEY=asd2....120asd
exec celery -A stargeo worker -l info
```

All the processes stop with it.
