### ISSUE TITLE
Default port behavior differs from Foreman

### ISSUE THREAD

**Issue by joeyespo** [nickstenning/honcho#123]
I was trying to use Honcho and Python 3 because Foreman was buggy with file handling, and I noticed some differences.

I set up [this gist](https://gist.github.com/joeyespo/3c210b2b6504531bc230) to test and demonstrate the differences:

- Foreman's port precedence is `-p option`, `.env file`, `PORT variable`, `default of 5000`
- Honcho's port precedence is `.env file`, `PORT variable`, `-p option`, `default of 5000`

**Comment by nickstenning** [comment]
Thank you for the report. Fixed by e0838bb and released as v0.6.3.
