### ISSUE TITLE
Please upload last code version to pip

### ISSUE THREAD

**Issue by rmuslimov** [nickstenning/honcho#130]
I'm often get this kind of error in my local development. I also know that this already has been fixed in latest code on github. So, please upload this version to PIP.

  File "/Users/rmuslimov/envs/fokker/lib/python2.7/site-packages/honcho/printer.py", line 22, in write
    self.output.write(*new_args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x87' in position 83: ordinal not in range(128)

Thanks!

**Comment by nickstenning** [comment]
Sorry for the delay! [Done!](https://pypi.python.org/pypi/honcho/0.6.1)
