### ISSUE TITLE
Can't stop exported upstart service

### ISSUE THREAD

**Issue by gamb** [nickstenning/honcho#131]
I have a simple Procfile:

```web: gunicorn myapp.wsgi --bind 0.0.0.0:$PORT --log-file -```

Exported to upstart with `honcho export -u deploy upstart /etc/init`. All good! `service myapp start` works fine, and `service myapp stop` appears to work, but upon inspecting `ps` I can see that the `gunicorn` proc. is still running.

**Comment by gamb** [comment]
Running honcho `0.5.0`.

The upstart configs generated are as follows:

```
=== myapp-web-1.conf ===

start on starting myapp-web
stop on stopping myapp-web
respawn

exec su - deploy -s /bin/sh -c 'cd /var/webapps/myapp; export PORT="6000"; AND_SOME_MORE_ENVIRONS=1; gunicorn myapp.wsgi --bind 0.0.0.0:$PORT --log-file - >> /var/log/myapp/web-1.log 2>&1'

=== myapp-web.conf ===

start on starting myapp
stop on stopping myapp

=== myapp.conf ===

pre-start script

bash << "EOF"
  mkdir -p /var/log/myapp
  chown -R deploy /var/log/myapp
EOF

end script

start on (started network-interface
          or started network-manager
          or started networking)

stop on (stopping network-interface
         or stopping network-manager
         or stopping networking)
```

**Comment by gamb** [comment]
Incidentally I notice that using `foreman 0.76.0` I have the same problem. A solution is discussed here: https://github.com/ddollar/foreman/issues/97

I don't have time to fix now, but will try to provide a patch when I can.

**Comment by slafs** [comment]
Thanks for the report. 

Just a quick note. In the current version of Honcho (not on PyPi yet) you can define and register your own export mechanisms. See https://honcho.readthedocs.org/en/latest/export.html#adding-new-export-format-support. So you can workaround your problem this way.

**Comment by nickstenning** [comment]
I suspect we could fix this just by adding an appropriate `exec` before the command...
