### ISSUE TITLE
Preserve colored output of subcommands in honcho start

### ISSUE THREAD

**Issue by Suor** [nickstenning/honcho#146]
This is my `Procfile`:
```
web: ./manage.py runserver
celery: celery -A stargeo worker -l info
```

Then I run `honcho start` output colors from both `runserver` (e.g. 404) and `celery` (warnings) are stripped. Would be nice to see that.

**Comment by karlin** [comment]
:+1:

**Comment by nickstenning** [comment]
Honcho doesn't strip colours from its output, as can be verified with this Procfile:

```
colour: echo '\033[31mhello world\033[0m'
```

These commands may well automatically strip colour if they detect their output is not a TTY. Indeed, for Django's `manage.py` that's [documented here](https://docs.djangoproject.com/en/1.9/ref/django-admin/#syntax-coloring).

If you can force them to continue to print ANSI colour codes, Honcho will preserve them.
