### ISSUE TITLE
don't run on windows python 2.7

### ISSUE THREAD

**Issue by s-trooper** [nickstenning/honcho#147]
seems know issue with python 2.7 but anyway, i hope to save time for another that will try this combination.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\Lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\Lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__

**Comment by akramparvez** [comment]
There is a work around for this issue. This issue occurs only if you use honcho.exe on windows with python 2.7, create a script with the following code and use this instead of honcho.exe

```
from honcho import command

if __name__ == "__main__":
    command.main()
```

**Comment by nickstenning** [comment]
This is [a known bug in Python 2.7](https://bugs.python.org/issue10845).

Upgrading to 2.7.11 should fix the issue.
