### ISSUE TITLE
Exported upstart configuration silently fails with quoted variables

### ISSUE THREAD

**Issue by migurski** [nickstenning/honcho#151]
At or near d8be8f4a8 (version 0.5.0), quoted variables in exported upstart scripts became invalid and fail silently. Previously, quoted `.env` variables with spaces generated upstart configurations with correctly-nested double and single quotes. This is an example generated by 84a1f7d (also version 0.5.0):

```
VAR="foo bar"
```

```
start on starting things-stuff
stop on stopping things-stuff
respawn

exec su - migurski -s /bin/sh -c 'cd /home/migurski/things; export PORT=5000; export VAR="foo bar"; python stuff.py >> /var/log/things/stuff-1.log 2>&1'
```

Starting at d8be8f4a8 and still in 0.6.6, the exported configuration from the configuration above began producing this invalid and failing upstart configuration, due to the single quotes:

```
start on starting things-stuff
stop on stopping things-stuff
respawn

exec su - migurski -s /bin/sh -c 'cd /home/migurski/things;export VAR='foo bar';export PORT=5000;python stuff.py >> /var/log/things/stuff-1.log 2>&1'
```

Here are my Procfile and python script for testing:

```
stuff: python stuff.py
```

```python
from sys import stderr
from os import environ
from time import sleep

while True:
	print >> stderr, repr(environ['VAR'])
	sleep(5)
```

**Comment by migurski** [comment]
I’m tracking the issue down to [`process.conf`](https://github.com/nickstenning/honcho/blob/d8be8f4a846b998fb2287429b254327a8d180b0c/honcho/export/templates/upstart/process.conf#L5) where `shellquote` is used. By default it uses single quotes. Overall it seems necessary to wrap the entirety of the argument to `exec` in quotes as well using [Jinja block assignments](http://jinja.pocoo.org/docs/dev/templates/#block-assignments), which are new in version 2.8.

**Comment by slafs** [comment]
Hey! Thanks for the report. Yeah... this seems like an edge case and a regression from v0.5.0. Could you contribute a test case for this issue? 
We should probably replicate ``quote`` function to use ``"`` in this case. Or maybe @msabramo has a better idea?

**Comment by migurski** [comment]
I will contribute a test!

**Comment by migurski** [comment]
:point_up: *poke*
