### ISSUE TITLE
Found a Encoding traceback when running with honcho.

### ISSUE THREAD

**Issue by codeskyblue** [nickstenning/honcho#152]
![image](https://cloud.githubusercontent.com/assets/3281689/8147553/e9dc2186-12a2-11e5-980a-5980a8976305.png)

**Comment by cosminstefanxp** [comment]
Same here. I think it's caused by a print (logging) made by one of the processes of a text containing unicode characters.

**Comment by cosminstefanxp** [comment]
Could be related to https://github.com/nickstenning/honcho/issues/51 ?

**Comment by nickstenning** [comment]
Honcho will use the I/O encoding of the Python interpreter running it. If you need it to print UTF-8 then you need to set up the environment (either using LANG/LC_ALL environment variables or by explicitly setting PYTHONIOENCODING).
