### ISSUE TITLE
`honcho run` doesn't parse non-option arguments correctly

### ISSUE THREAD

**Issue by benwilber** [nickstenning/honcho#159]
```
$ honcho run -- make
/bin/sh: --: invalid option
Usage:	/bin/sh [GNU long option] [option] ...
	/bin/sh [GNU long option] [option] script-file ...
...
```
Everything after `--` should be considered the command (with arguments) to run.

**Comment by ekonstantinidis** [comment]
I'm having the same issue with the run command. Example:

    env/bin/honcho --app-root etc/environments/staging run -- 'python manage.py collectstatic --noinput

    /bin/sh: --: invalid option
    Usage:	/bin/sh [GNU long option] [option] ...
	    /bin/sh [GNU long option] [option] script-file ...
