### ISSUE TITLE
Document using honcho as a process manager

### ISSUE THREAD

**Issue by mattrobenolt** [nickstenning/honcho#169]
Honcho is great and it's simple to use as a library, but I had to just kinda reverse engineer what was going to to figure out how to do so. But being able to just leverage the `honcho.manager:Manager` makes it super simple to replace other subprocess managing.

Inside Sentry, we were doing this by hand, which was a bit annoying. I replaced our `sentry devserver` command to utilize `honcho` without needing to use a Procfile (since our processes are already defined by Sentry itself) and this is super seamless.

So I'm just requesting to add some documentation for this since it wasn't clear on how to do this without reverse engineering `honcho.command:command_run` and figuring it out.

For context: https://github.com/getsentry/sentry/pull/2905

Thanks. :heart:

**Comment by nickstenning** [comment]
Hi there. It's great to hear you're using Honcho programatically for the Sentry development server. If you're interested in helping to improve Honcho's documentation, that would be great. Any such help would be gratefully received.

PRs to the documentation or code are most welcome.
