### ISSUE TITLE
Nor .env or environment variable PORT is used as port

### ISSUE THREAD

**Issue by alej0varas** [nickstenning/honcho#17]
While environment variable PORT is set to 8000 or a .env file containing PORT=8000 exists, honcho still use 5000 as the port value.

**Comment by eelkevdbos** [comment]
This ticket saved me another hour of debugging. 

For those interested: https://ddollar.github.io/foreman/#PROCFILE

> The special environment variables $PORT and $PS are available within the Procfile. $PORT is the port selected for that process. $PS is the name of the process for the line.

> The $PORT value starts as the base port as specified by -p, then increments by 100 for each new process line. Multiple instances of the same process are assigned $PORT values that increment by 1.
