### ISSUE TITLE
-f argument before command is suppressed

### ISSUE THREAD

**Issue by marckrull** [nickstenning/honcho#173]
System information: Mac OS X, 10.11.1
Honcho version: 0.7.0

With the latest release of honcho (0.7.0), I've noticed that the -f argument is processed properly **after** a command, but not **before** a command.  -e and -d arguments don't exhibit this order-dependent behavior.

Examples:
```
$ honcho -f my_procfile check
2016-04-12 23:49:22 [45546] [ERROR] Procfile does not exist or is not a file
$ honcho check -f my_procfile
2016-04-12 23:49:24 [45548] [INFO] Valid procfile detected (postgres, rabbit, redis, flower)
```

**Comment by nickstenning** [comment]
I've just released v0.7.1 which includes the fixes provided by Marc. Thank you again!
