### ISSUE TITLE
Upload non-wheel format to pypi

### ISSUE THREAD

**Issue by mattrobenolt** [nickstenning/honcho#177]
Right now, only `.whl` files are being uploaded, which breaks for a version of `pip` that doesn't support wheels. Should upload the `.tar.gz` version as well as a result of `setup.py sdist`.

**Comment by DaveBlooman** [comment]
Any chance we can get this issue resolved, can't deploy at the moment

**Comment by nickstenning** [comment]
I've just uploaded the sdist for 0.7.1.

**Comment by DaveBlooman** [comment]
Thanks, resolved my issue
