### ISSUE TITLE
Honcho export in Anaconda environment

### ISSUE THREAD

**Issue by bzamecnik** [nickstenning/honcho#185]
Hi,
I tried to run honcho in an Anaconda environment and export the startup scripts for upstart.
At least running `honcho start` is possible by first activating the env:

```
source activate my_env && honcho start
```

However, exporting the init scripts does not work. It requires root permission but when I run `sudo honcho export -a myapp upstart /etc/init` it fails with `sudo: honcho: command not found` because for the root user there's no conda installation.

The only workaround I was able to do was to export the `*.conf` file as the user with conda env to a writable location, then move them to `/etc/init` and modify to add call to `source activate my_env`.

Can anyone imagine some more straightforward way? Thanks.

**Comment by nickstenning** [comment]
The workaround you've found sounds like the solution I would expect. In general I would not advise running `honcho` as root.
