### ISSUE TITLE
Cannot tail -f | jq

### ISSUE THREAD

**Issue by ptbrowne** [nickstenning/honcho#197]
When I do 

```
logs: tail -f logs
```

everything is OK, but when I do 

```
logs: tail -f logs | jq '.'
```

I have no output :/ Same if I do 

```
logs: bash -c "tail -f logs | jq '.'"
```

I tried to do launch honcho with `env PYTHONUNBUFFERED=1 honcho start' but to no avail.

Is there any solution ?

**Comment by nickstenning** [comment]
Yup, there's a solution!

First of all, you should be able to verify that this isn't a honcho issue by running

```
tail -f logs | jq '.' | less
```

You'll see the same problem -- no output.

But you can override the buffering mode of STDOUT for jq using [`stdbuf(1)`](https://linux.die.net/man/1/stdbuf):

```
tail -f logs | stdbuf -oL jq '.' | less
```

Or, for honcho:

```Procfile
logs: tail -f logs | stdbuf -oL jq '.'
```

**Comment by ptbrowne** [comment]
Thanks !
