### ISSUE TITLE
honcho start fails under High Sierra

### ISSUE THREAD

**Issue by BarrySmith** [nickstenning/honcho#198]
$ honcho start
08:48:46 system     | listener.1 started (pid=93777)
08:48:46 system     | tunnel.1 started (pid=93778)
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="no configuration paths supplied"
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="using configuration at default config path" path=/Users/barrysmith/.ngrok2/ngrok.yml
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="open config file" path=/Users/barrysmith/.ngrok2/ngrok.yml err=nil
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="run component" obj=controller comp="signal handler"
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="run component" obj=controller comp="memory storage"
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="run component" obj=controller comp="Tunnel session"
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="run component" obj=controller comp=web
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="run component" obj=controller comp=updater
08:48:46 tunnel.1   | t=2018-02-06T08:48:46-0600 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040
08:48:46 listener.1 | Traceback (most recent call last):
08:48:46 listener.1 |   File "listener.py", line 5, in <module>
08:48:46 listener.1 |     from pync import Notifier
08:48:46 listener.1 |   File "build/bdist.macosx-10.13-intel/egg/pync/__init__.py", line 3, in <module>
08:48:46 listener.1 |   File "build/bdist.macosx-10.13-intel/egg/pync/TerminalNotifier.py", line 130, in <module>
08:48:46 listener.1 |   File "build/bdist.macosx-10.13-intel/egg/pync/TerminalNotifier.py", line 37, in __init__
08:48:46 listener.1 | Exception: pync was not properly installed. Head over to https://github.com/SeTeM/pync/ and file a bug.
08:48:46 system     | listener.1 stopped (rc=1)
08:48:46 system     | sending SIGTERM to tunnel.1 (pid 93778)
08:48:46 system     | tunnel.1 stopped (rc=-15)

Going to https://github.com/SeTeM/pync/ says it is no longer supported. How do we rig honcho to not use pync? 

I am following directions from https://confluence.atlassian.com/bitbucket/tutorial-create-and-trigger-a-webhook-747606432.html

**Comment by nickstenning** [comment]
Hi @BarrySmith! Thanks for opening this issue. I don't think what you're seeing here is a problem with Honcho. It looks to me like the `listener` process defined in your Procfile is the one complaining about pync, as everything after the pipe character (`|`) is output from the program Honcho is running, rather than output from Honcho itself.

I'm going to preemptively close this issue, but feel free to reopen it if you think I've misinterpreted you and this really is a Honcho problem.
