### ISSUE TITLE
Virutalenv on Windows + *nix

### ISSUE THREAD

**Issue by daninfpj** [nickstenning/honcho#204]
I'm using virtualenv on my project and have a Procfile that includes this line:

`web: source venv/bin/activate && python manage.py runserver`

I run honcho with this command:

`venv/bin/honcho start`

That works perfectly on a *nix system, however on Windows it does not.

I can run honcho using:

`venv\Scripts\honcho start`

But the `source venv/bin/activate` command fails since the command to activate virtualenv is different. If I remove it, honcho won't load the virtualenv and the project won't run either.

How would you go about this?

**Comment by kryskool** [comment]
I think on Windows it's better to use [Pipenv](https://github.com/pypa/pipenv)

`web: pipenv run python manage.py runserver`

**Comment by nickstenning** [comment]
I'm going to go ahead and close this issue. The issue of ensuring the commands you're running work in all the environments you want to run Honcho in is out of scope for Honcho itself.
