### ISSUE TITLE
Dashes in process types

### ISSUE THREAD

**Issue by johndgiese** [nickstenning/honcho#206]
I believe that process types, according to this [Heroku page](https://devcenter.heroku.com/articles/procfile), must be alphanumeric.

If I create a Procfile with the following content

```
process-type-with-dashes: python -c 'print("hello")'
```

and then run `honcho start`, honcho fails silently.

Also, when I run `honcho check`, it says it is a valid Procfile.

Perhaps it would be helpful if:
- `honcho start` would complain if there is an invalid Procfile
- `honcho check` complains if the process types have dashes

I am using honcho v1.0.1 with python 3.7.0 on macOS.

Thank you for all of your work, I wish I had time to create a PR for this, but I figured creating an issue was better than nothing.

**Comment by nickstenning** [comment]
Huh, interesting. I certainly agree that `honcho check` and `honcho start` should agree on this! Will check.
