### ISSUE TITLE
Stop honcho from Makefile

### ISSUE THREAD

**Issue by alper** [nickstenning/honcho#214]
We have a rather hacky Makefile where I'm looking to replace a bunch of stuff with `honcho start` but I'm not finding an equivalent stop command.

The thing is we have some functional tests for which  the python stuff needs to run and when those tests have been done it needs to be stopped again. Any way to address this using honcho?

The current approach stores a PID and then kills that I believe.

**Comment by nickstenning** [comment]
Perhaps I'm misunderstanding the question, but `honcho start` runs a foreground process, so the idea of a `honcho stop` command doesn't make a great deal of sense to me.

**Comment by alper** [comment]
Yeah, I get that but say we use the `honcho` command in our testing sequence to start everything before doing functional tests, we would like to tear everything down again.

I get that we could start things manually maybe but honcho is a compact and DRY way to start everything that needs to be started.

**Comment by jacebrowning** [comment]
@alper One option is to run your tests with `honco` as well:

```
# Procfile.e2e

app: python manage.py runserver
test: pytest e2e_tests
```

via `honcho --procfile Procfile.e2e`. I have an example of this pattern [here](https://github.com/jacebrowning/template-django-demo/blob/ebbfe20b0083aa8194502c563e42d21dd81def83/Makefile#L158-L160).

**Comment by alper** [comment]
Ah, thanks. That's quite clever!

**Comment by nickstenning** [comment]
Closing this as I don't believe there are any changes in Honcho needed here.
