### ISSUE TITLE
[bug] Subparsers override common common_args

### ISSUE THREAD

**Issue by basepi** [nickstenning/honcho#215]
Simple way to reproduce this issue:

```
honcho --no-prefix start  # fails, prefixes are present
honcho start --no-prefix  # succeeds, prefixes are gone
```

This is because the [common_args](https://github.com/nickstenning/honcho/blob/f3b2e1e11868283f4c3463102b7ed3bd00f26b32/honcho/command.py#L32-L53) are added both [to the base parser](https://github.com/nickstenning/honcho/blob/f3b2e1e11868283f4c3463102b7ed3bd00f26b32/honcho/command.py#L59) and [to the start subparser](https://github.com/nickstenning/honcho/blob/f3b2e1e11868283f4c3463102b7ed3bd00f26b32/honcho/command.py#L240). However, they are not namespaced, which means that the default for the subparser arg will override the parser arg even if it's present.

The "correct" fix is to only allow common args before the subcommand. This is also how the `--help` reads, so it would match that better. If you wanted to allow common args on either side, I think you'd have to namespace them and combine them after parsing.

**Comment by nickstenning** [comment]
Thank you for reporting! Fixed by ed3fdd2ce2d2b125909256c71cf5d0f8882b7e13.
