### ISSUE TITLE
Honcho buffers output to file

### ISSUE THREAD

**Issue by MeabhG** [nickstenning/honcho#217]
When Honcho receives output from the processes it starts it buffers it before flushing to file.
Adding `self.output.flush()` [here](https://github.com/nickstenning/honcho/blob/master/honcho/printer.py#L61) (could be controlled by a config variable) would allow it to be line buffered. But there might be a better solution.

How to reproduce:

**printing.py**
```
import time
from datetime import datetime
import logging

logging.basicConfig(level=logging.INFO)

while 1:
    time.sleep(1)
    logging.info("Process printing.py output at: {}".format(datetime.now()))
```

**run.sh**
```
#!/usr/bin/env bash

pip install honcho
exec honcho start --procfile /etc/honcho/Procfile
```

**Procfile**
```
web0: python printing.py
```

**Python no buffering**
`docker run -d --rm --name honcho -v $(pwd)/printing.py:/printing.py --entrypoint /usr/local/bin/python docker-hub.ihs.demonware.net/python:3.7.5-stretch /printing.py`
and
`docker logs -f honcho` in a second terminal to show line buffered logs

**honcho buffering**
`docker run -d --rm --name honcho -v $(pwd)/printing.py:/printing.py -v $(pwd)/run.sh:/run.sh -v $(pwd)/Procfile:/etc/honcho/Procfile  --entrypoint bash docker-hub.ihs.demonware.net/python:3.7.5-stretch /run.sh`
and 
`docker logs -f honcho` in a second terminal to show `honcho` buffered logs (wait a few minutes for log dump)

Same behaviour with `docker-hub.ihs.demonware.net/python:2.7.16-stretch`

**Comment by nickstenning** [comment]
This has been a constant bugbear of mine. Python's default behaviour is to buffer writes to STDOUT when STDOUT is not a TTY.

I've changed Honcho's behaviour in d12e85f to always line-buffer output.

**Comment by MeabhG** [comment]
Thanks @nickstenning
