### ISSUE TITLE
PROCFILE envvar is respected only if provided on .env file

### ISSUE THREAD

**Issue by alanjds** [nickstenning/honcho#222]
From the docs and the lines ahead, one (like me) can understand that PROCFILE envvar is respected from any environment source, not only from `.env` file.

https://github.com/nickstenning/honcho/blob/a460b31e4c6af9971a8755a6cf211803629d3bec/honcho/command.py#L345-L347

The envvar PROCFILE is ignored if passed by shell environment

```console
$ honcho --version
honcho 1.0.1
$ ls loadtest/Procfile 
loadtest/Procfile
$ PROCFILE=loadtest/Procfile honcho start
2020-07-10 11:32:32 [24851] [ERROR] Procfile does not exist or is not a file
```

**Comment by nickstenning** [comment]
Thank you for reporting this. It should be fixed on `main` and I hope to have another release out soon.
