### ISSUE TITLE
Why isn't there "stop" command?

### ISSUE THREAD

**Issue by naddika** [nickstenning/honcho#224]
There're "run" and "start". Why isn't there "stop"? How should one stop the processes then?

**Comment by nickstenning** [comment]
Honcho runs in the foreground. The processes stop when you stop or kill honcho (with Ctrl-C, for example). Conversely, honcho stops when the processes stop.

**Comment by naddika** [comment]
My goal is to  run and stop the processes in a Procfile all at once. Therefore, to stop the process will I have to kill the Honcho process only?

**Comment by nickstenning** [comment]
Try it! If you Ctrl-C honcho, it will kill all the processes running under it.

**Comment by naddika** [comment]
Yeah, a bash script, apparently, has human hands and eyes, and can understand my commands given him by voice.
