### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by guettli** [nickstenning/honcho#225]
Hi,

the last release on pypi is from 2017.

There are several commits in the git repo after 2017.

Maybe it is time for a new release?

**Comment by lbenc135** [comment]
@nickstenning If you need help maintaining this project I'd be happy to help, since we're using it a lot at my company

**Comment by nickstenning** [comment]
Hey folks! Thanks for all the offers of help and the nudges. I've just release v1.1.0.

https://github.com/nickstenning/honcho/releases/tag/v1.1.0

**Comment by joshfriend** [comment]
Outstanding 😄 thank you!
