### ISSUE TITLE
start honcho application at start app

### ISSUE THREAD

**Issue by lfaino** [nickstenning/honcho#245]
Dear,

this is not really an issue but  i would like to know how to run honcho application at start up in Ubuntu 20.04

thanks
L

**Comment by Xdynix** [comment]
Some options:

1. Create a new systemd service that run honcho application. (e.g. [a random Google search result](https://www.shubhamdipt.com/blog/how-to-create-a-systemd-service-in-linux/))
2. Wrap your honcho application as a Docker container. And let Docker to restart it each time start up.
3. Some other options mentioned [here](https://www.baeldung.com/linux/run-script-on-startup).

Personally I prefer the Docker solution. Not too much manual work needed.
