### ISSUE TITLE
3.12 compat

### ISSUE THREAD

**Issue by aodj** [nickstenning/honcho#247]
It looks like the `pkg_resources` library was removed/migrated in Python 3.12 breaking `honcho`. From mu-editor/mu#2485

> From the `pkg_resources` docs: [setuptools.pypa.io/en/latest/pkg_resources.html](https://setuptools.pypa.io/en/latest/pkg_resources.html)
> 
> > Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.
> 
> Python 3.12 has removed `pkg_resources` from the standard library (moved to `setuptools`): [docs.python.org/3/whatsnew/3.12.html](https://docs.python.org/3/whatsnew/3.12.html)
> 
> > [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/3/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/3/library/venv.html#venv-explanation) virtual environment.
> 
> ...
> 
> Good news is that the `importlib_resources` backport library contains documentation on how to migrate: [importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename](https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename)

**Comment by confuzeus** [comment]
It looks like  `entry_points` from [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) should be used instead of `iter_entry_points` from `pkg_resources`.
