### ISSUE TITLE
The output of honcho looks weird

### ISSUE THREAD

**Issue by pombredanne** [nickstenning/honcho#35]
For instance the weird control chars in this:
```
←[36m15:27:19 es.1   | ←[0mstarted with pid 2952
←[33m15:27:19 task.1 | ←[0mstarted with pid 5012
←[32m15:27:19 web.1  | ←[0mstarted with pid 4640
```
Is this to color things in the shell? if so that would not port well to non-posix...
Is this out of compatibility with Foreman?
Is this something that could be optionally disabled with a command flag?

**Comment by nickstenning** [comment]
Finally fixed in v0.6.2 (by a1b2cb5).
