### ISSUE TITLE
Undocumented PORT behavior is surprising

### ISSUE THREAD

**Issue by kcarnold** [nickstenning/honcho#64]
I have one webserver that looks for PORT in its environment, and a few other processes that do bookkeeping with the database and so don't have a listening port. I converted a previous script that manually set PORT= in the webserver's environment over to Honcho, and I couldn't understand why the webserver wasn't listening on the port I specified.

It turns out that I was hitting the undocumented PORT management feature, and I understand the usefulness of that, and how it's there to match Foreman's behavior (which is also mostly undocumented). I just put the webserver first, and it works now. But having PORT change based on Procfile ordering was surprising.

**Comment by nickstenning** [comment]
This behaviour may be surprising, but it's half the point of honcho. Closing. Feel free to submit changes to the documentation if you get a moment. I will get around to it myself one of these days...
