### ISSUE TITLE
Exported supervisord conf fails with certain characters in Procfile

### ISSUE THREAD

**Issue by davepgreene** [nickstenning/honcho#73]
**System:**
http://aws.amazon.com/amazon-linux-ami/

**Steps to reproduce the bug:**
`honcho export supervisord /etc/supervisord.d/app.conf`

**Use case (in Procfile):**
```
scheduler: /home/user/project/virtual_env/bin/celery worker --beat --events --maxtasksperchild=1000 --hostname=scheduler.%h --app=webapp
```

The export command doesn't add an extra `%` character to escape existing `%` characters per the supervisor documentation:

>`environment`

>A list of key/value pairs in the form KEY="val",KEY2="val2" that will be placed in the supervisord process’ environment (and as a result in all of its child process’ environments). This option can include the value %(here)s, which expands to the directory in which the supervisord configuration file was found. Values containing non-alphanumeric characters should be quoted (e.g. KEY="val:123",KEY2="val,456"). Otherwise, quoting the values is optional but recommended. To escape percent characters, simply use two. (e.g. URI="/first%%20name") Note that subprocesses will inherit the environment variables of the shell used to start supervisord except for the ones overridden here and within the program’s environment option.
> -- <cite>http://supervisord.org/configuration.html#supervisord-section-values</cite>

**Comment by codeskyblue** [comment]
I fixed with start `supervisord --strip_ansi`
