### ISSUE TITLE
Exported supervisord conf doesn't handle environmental variables well

### ISSUE THREAD

**Issue by davepgreene** [nickstenning/honcho#74]
**System:**
http://aws.amazon.com/amazon-linux-ami/

**Steps to reproduce the bug:**
`honcho -f Procfile -e .env export supervisord /etc/supervisord.d/app.conf`

**Use case (in Procfile):**
```
web: $VENV_HOME/bin/newrelic-admin run-program $VENV_HOME/bin/gunicorn -c $SRC_HOME/gunicorn.py wsgi:application
```

The export command doesn't handle environmental variables found in the system `$ env` or the `.env` file loaded by `honcho`.

> `command`

> The command that will be run when this program is started. The command can be either absolute (e.g. /path/to/programname) or relative (e.g. programname). If it is relative, the supervisord's environment $PATH will be searched for the executable. Programs can accept arguments, e.g. /path/to/program foo bar. The command line can use double quotes to group arguments with spaces in them to pass to the program, e.g. /path/to/program/name -p "foo bar". Note that the value of command may include Python string expressions, e.g. /path/to/programname --port=80%(process_num)02d might expand to /path/to/programname --port=8000 at runtime. String expressions are evaluated against a dictionary containing the keys group_name, host_node_name, process_num, program_name, here (the directory of the supervisord config file), and all **supervisord's environment variables prefixed with ENV_**.
> --<cite>http://supervisord.org/configuration.html#program-x-section-values</cite>

Note my emphasis.

`honcho` should either expand environmental variables or prefix them with `ENV_` as per supervisord's documentation.

**Comment by nickstenning** [comment]
As of v0.6.0 Honcho will now correctly write environment vars from `.env` files into the supervisord export format.
