### ISSUE TITLE
Docs for export options don't match `honcho help export`

### ISSUE THREAD

**Issue by msabramo** [nickstenning/honcho#98]
https://honcho.readthedocs.org/en/latest/export.html has:

```
-s SHELL, --shell SHELL
    Specify the shell that should run the application.
    Only used for upstart.

-u USER, --user USER
    Specify the user the application should be run as.

-a APP, --app APP
    Specify the name of the application you are going to export.

-c process=num,process=num, --concurrency process=num,process=num
    Specify the number of each process type to run.

-p N, --port N
    Specify which port to use as the base for this application.
    Should be a multiple of 1000.

-l DIR, --log DIR
    Specify the directory to place process logs in.
```

OTOH, the built-in help says:

```
$ honcho help export
...
  -a APP, --app APP     alternative app name (default: honcho)
  -l DIR, --log DIR     directory to place process logs in (default:
                        /var/log/APP)
  -p N, --port N
  -c process=num,process=num, --concurrency process=num,process=num
                        number of each process type to run. (default: None)
  -u USER, --user USER  user the application should run as (default: None)
  -s SHELL, --shell SHELL
                        the shell that should run the application (default:
                        /bin/sh)
```

They are close, but there are some subtle differences.

* readthedocs says of `--shell`: "Only used for upstart" (which [isn't true](https://github.com/nickstenning/honcho/blob/master/honcho/data/export/supervisord/supervisord.conf#L3)). The help doesn't (more accurate).
* The help doesn't have a description for the `-p`/`--port` option. readthedocs is better here (unless the "Should be a multiple of 1000" bit isn't true, which I didn't verify).
* readthedocs version is more verbose. All option descriptions start with "Specify..."
* listed in different order (this isn't so important, except that it makes it a little hard to check whether they match each other

**Comment by nickstenning** [comment]
I've removed the duplication of the help output in 7f34569.
